/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../Drivers/Device/stm32l476xx.h"

#define SYSTEMCLK 4000000
// SYSTICK DELAY
void SysTick_Init(void){
	SysTick->CTRL = 0;
	SysTick->LOAD = (SYSTEMCLK / 1000) - 1; // 1 ms tick
	SysTick->VAL = 0;
	SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;
}

void msdelay(uint32_t ms){
	for (uint32_t i = 0; i < ms; i++){
		while ((SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk) == 0){}
	}
}


int main(void)
{
	SysTick_Init();

	// GPIO PORT B CLOCK ENABLE
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;

	GPIOB->MODER &= ~GPIO_MODER_MODE2_Msk;
	GPIOB->MODER |= (1<< GPIO_MODER_MODE2_Pos);

    while(1){
    		GPIOB->ODR ^= GPIO_ODR_OD2;

    		msdelay(1000);
    }
}
